# Generated by Django 5.1.11 on 2025-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marque para a página ficar visível públicamente.'),
        ),
    ]
