# Generated by Django 5.1.11 on 2025-07-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exerpt',
            new_name='excerpt',
        ),
    ]
